# Prometheus configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ocr-service'
    static_configs:
      - targets: ['ocr-service:9090']
  
  - job_name: 'web-app'
    static_configs:
      - targets: ['web-app:8001']
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
  
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
